version: '3.1'

services:
  api:
    build: 
      dockerfile: api.Dockerfile
    ports:
      - '3001:3001'
  app:
    build:
      dockerfile: app.Dockerfile
    ports: 
      - '3000:3000'
    depends_on:
      - api
